updated examples

diff --git a/BSKL/xinstall-edirect b/BSKL/xinstall-edirect
--- a/BSKL/xinstall-edirect
+++ b/BSKL/xinstall-edirect
@@ -1,43 +1,149 @@
 #!/bin/bash
-#
-# Installing NCBI edirect utilities into the current directory ...
 
-INSTALLDIR=`pwd`
+# Public domain notice for all NCBI EDirect scripts is located at:
+# https://www.ncbi.nlm.nih.gov/books/NBK179288/#chapter6.Public_Domain_Notice
 
-echo "Installing NCBI edirect utilities into $INSTALLDIR ..."
-echo ""
+base="ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect"
 
-perl -MNet::FTP -e \
-    '$ftp = new Net::FTP("ftp.ncbi.nlm.nih.gov", Passive => 1);
-    $ftp->login; $ftp->binary;
-    $ftp->get("/entrez/entrezdirect/edirect.tar.gz");'
-gunzip -c edirect.tar.gz | tar xf -
-rm edirect.tar.gz
+# function to fetch a single file, passed as an argument
+FetchFile() {
 
-# Adding accessory programs:
-#
+  fl="$1"
+
+  if [ -x "$(command -v curl)" ]
+  then
+    curl -s "${base}/${fl}" -o "${fl}"
+  elif [ -x "$(command -v wget)" ]
+  then
+    wget "${base}/${fl}"
+  else
+    echo "Missing curl and wget commands, unable to download EDirect archive" >&2
+    exit 1
+  fi
+}
+
+# edirect folder to be installed in the current directory
+echo "edirect will be installed in the current directory: ${PWD}"
+
+# download and extract edirect archive
+FetchFile "edirect.tar.gz"
+if [ -s "edirect.tar.gz" ]
+then
+  gunzip -c edirect.tar.gz | tar xf -
+  rm edirect.tar.gz
+fi
+if [ ! -d "edirect" ]
+then
+  echo "Unable to download EDirect archive" >&2
+  exit 1
+fi
+
+# remaining executables to be installed within edirect folder
 cd edirect
-wget https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/xtract.Linux.gz
-gunzip xtract.Linux.gz 
-chmod a+x xtract.Linux 
 
-wget https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/transmute.Linux.gz
-gunzip -f transmute.Linux.gz 
-chmod a+x transmute.Linux 
+# get path for configuration file assistance commands
+DIR=$( pwd )
 
-wget https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/rchive.Linux.gz
-gunzip -f rchive.Linux.gz 
-chmod a+x rchive.Linux 
+# determine current computer platform
+osname=$(uname -s)
+cputype=$(uname -m)
+case "$osname-$cputype" in
+  Linux-x86_64 )           plt=Linux ;;
+  Darwin-x86_64 )          plt=Darwin ;;
+  Darwin-*arm* )           plt=Silicon ;;
+  CYGWIN_NT-* | MINGW*-* ) plt=CYGWIN_NT ;;
+  Linux-*arm* )            plt=ARM ;;
+esac
 
-# Finishing up:
-#
-echo "" >> ~/.profile
-echo "# set PATH so it includes the edirect if it exists" >> ~/.profile
-echo "if [ -d  $INSTALLDIR/edirect  ] ; then" >> ~/.profile
-echo "    PATH=$PATH:$INSTALLDIR/edirect" >> ~/.profile
-echo "fi" >> ~/.profile
+# fetch appropriate precompiled versions of xtract, rchive, and transmute
+if [ -n "$plt" ]
+then
+  for exc in xtract rchive transmute
+  do
+    FetchFile "$exc.$plt.gz"
+    gunzip -f "$exc.$plt.gz"
+    chmod +x "$exc.$plt"
+  done
+fi
 
+# offer to edit the PATH variable assignment command in configuration files
 echo ""
-echo "One more step:"
+echo "Entrez Direct has been successfully downloaded and installed."
 echo ""
-echo "Execute 'source ~/.profile' to update your PATH variable."
+
+prfx="In order to complete the configuration process, please execute the following:"
+advice=`mktemp`
+
+target=bash_profile
+if ! grep "$target" "${PWD}/.bashrc" >/dev/null 2>&1
+then
+  if [ ! -f ${PWD}/.$target ] || grep 'bashrc' "${PWD}/.$target" >/dev/null 2>&1
+  then
+    target=bashrc
+  else
+    if [ -n "$prfx" ]
+    then
+      printf "$prfx\n\n"
+      prfx=""
+    fi
+    printf "  echo \"source ~/.bash_profile\" >> \${PWD}/.bashrc\n" | tee $advice
+  fi
+fi
+if ! grep "PATH.*edirect" "${PWD}/.$target" >/dev/null 2>&1
+then
+  if [ -n "$prfx" ]
+  then
+    printf "$prfx\n\n"
+    prfx=""
+  fi
+  printf "  echo \"export PATH=\\\${PATH}:${DIR}\" >> \${PWD}/.$target\n" | tee -a $advice
+fi
+zarget=zshrc
+if [ "$osname" = "Darwin" ]
+then
+  if [ ! -f ${PWD}/.zshrc ] && [ -f ${PWD}/.zprofile ] >/dev/null 2>&1
+  then
+    zarget=zprofile
+  fi
+  if ! grep "PATH.*edirect" "${PWD}/.$zarget" >/dev/null 2>&1
+  then
+    if [ -n "$prfx" ]
+    then
+      printf "$prfx\n\n"
+      prfx=""
+    fi
+    printf "  echo \"export PATH=\\\${PATH}:${DIR}\" >> \${PWD}/.$zarget\n" | tee -a $advice
+  fi
+fi
+
+if [ -z "$prfx" ]
+then
+  echo ""
+  if [ "$osname" = "Darwin" ]
+  then
+    echo "or manually edit the PATH variable assignments in your .$target and .$zarget files."
+  else
+    echo "or manually edit the PATH variable assignment in your .$target file."
+  fi
+  echo ""
+  echo "Would you like to do that automatically now? [y/N]"
+  read response
+  case "$response" in
+    [Yy]*      ) . $advice; echo "OK, done." ;;
+    [Nn]* | '' ) echo "Holding off, then." ;;
+    *          ) echo "Conservatively taking that as a no." ;;
+  esac
+fi
+rm $advice
+
+case ":$PATH:" in
+  *:$PWD/edirect:*)
+    ;;
+  *)
+    echo ""
+    echo "To activate EDirect for this terminal session, please execute the following:"
+    echo ""
+    printf "export PATH=\${PATH}:\${PWD}/edirect\n"
+    echo ""
+    ;;
+esac
